services:
  - docker

env:
  - IMAGE_TAG=v2.0.1
  - IMAGE_REPOSITORY="quay.io/helmpack/chart-testing"

before_script:
  - docker container run --interactive --tty --detach --volume "$(pwd):/workdir" --workdir /workdir "$IMAGE_REPOSITORY:$IMAGE_TAG"

script:
  - echo hello
